block0 = '''minecraft:barrel[facing=up]'''

block1 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b} ]}'''

block2 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b} ]}'''

block3 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b} ]}'''

block4 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b} ]}'''

block5 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b} ]}'''

block6 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b} ]}'''

block7 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b} ]}'''

block8 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b} ]}'''

block9 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, Count:1b} ]}'''

block10 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, Count:1b} ]}'''

block11 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, Count:1b} ]}'''

block12 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, Count:1b} ]}'''

block13 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:22b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:23b, Count:1b} ]}'''

block14 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:22b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:23b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:24b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:25b, Count:1b} ]}'''

block15 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, Count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:22b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:23b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:24b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:25b, Count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:26b, Count:1b} ]}'''

block = [
    block0,
    block1,
    block2,
    block3,
    block4,
    block5,
    block6,
    block7,
    block8,
    block9,
    block10,
    block11,
    block12,
    block13,
    block14,
    block15
]
