block0 = '''minecraft:barrel[facing=up]'''.replace("\n", "").replace(" ", "")

block1 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block2 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block3 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block4 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block5 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block6 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block7 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block8 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block9 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block10 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block11 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block12 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block13 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:22b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:23b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block14 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:22b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:23b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:24b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:25b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block15 = '''minecraft:barrel[facing=up]{Items:[ {id:"minecraft:totem_of_undying", Slot:0b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:1b, count:1b}, 
                                                {id:"minecraft:totem_of_undying", Slot:2b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:3b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:4b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:5b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:6b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:7b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:8b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:9b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:10b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:11b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:12b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:13b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:14b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:15b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:16b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:17b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:18b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:19b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:20b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:21b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:22b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:23b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:24b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:25b, count:1b},
                                                {id:"minecraft:totem_of_undying", Slot:26b, count:1b} ]}'''.replace("\n", "").replace(" ", "")

block = [
    block0,
    block1,
    block2,
    block3,
    block4,
    block5,
    block6,
    block7,
    block8,
    block9,
    block10,
    block11,
    block12,
    block13,
    block14,
    block15
]
